const SEARCH_TARGETS = Object.freeze({
  SERVICE: 'SERVICE',
  BOOKMARK: 'BOOKMARK',
  RECENT: 'RECENT',
  READING_QUEUE: 'READING_QUEUE',
  COMMAND_SUGGESTION: 'COMMAND_SUGGESTION',
  COMMAND: 'COMMAND'
})
module.exports = SEARCH_TARGETS
