// Try to keep these generic to support n-types of account
module.exports = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  DEFAULT: 'DEFAULT',
  STORAGE: 'STORAGE',
  CONTACTS: 'CONTACTS',
  NOTES: 'NOTES',
  CALENDAR: 'CALENDAR',
  PHOTOS: 'PHOTOS',
  COMMUNICATION: 'COMMUNICATION',
  SOCIAL: 'SOCIAL',
  ANALYTICS: 'ANALYTICS',
  VIDEO: 'VIDEO',
  MESSENGER: 'MESSENGER',
  DOCS: 'DOCS',
  SHEETS: 'SHEETS',
  SLIDES: 'SLIDES'
})
