module.exports = {
  GoogleCalendarService: require('./GoogleCalendarService'),
  GoogleCommunicationService: require('./GoogleCommunicationService'),
  GoogleContactsService: require('./GoogleContactsService'),
  GoogleDefaultService: require('./GoogleDefaultService'),
  GoogleNotesService: require('./GoogleNotesService'),
  GoogleMailbox: require('./GoogleMailbox'),
  GooglePhotosService: require('./GooglePhotosService'),
  GoogleStorageService: require('./GoogleStorageService'),
  GoogleAnalyticsService: require('./GoogleAnalyticsService'),
  GoogleDocsService: require('./GoogleDocsService'),
  GoogleMessengerService: require('./GoogleMessengerService'),
  GoogleSheetsService: require('./GoogleSheetsService'),
  GoogleSlidesService: require('./GoogleSlidesService'),
  GoogleSocialService: require('./GoogleSocialService'),
  GoogleVideoService: require('./GoogleVideoService'),
  GoogleMusicService: require('./GoogleMusicService'),
  GoogleAdminService: require('./GoogleAdminService'),
  GoogleFiService: require('./GoogleFiService'),
  GoogleClassroomService: require('./GoogleClassroomService')
}
