const RENDER_PROCESS_PREFERENCE_TYPES = Object.freeze({
  WB_LAUNCH_SETTINGS: 'WB_LAUNCH_SETTINGS',
  WB_CREXTENSION_CONTENTSCRIPT_CONFIG: 'WB_CREXTENSION_CONTENTSCRIPT_CONFIG'
})

module.exports = {
  RENDER_PROCESS_PREFERENCE_TYPES: RENDER_PROCESS_PREFERENCE_TYPES
}
