module.exports = Object.freeze({
  // Events
  WBRPC_WC_DOM_READY: 'WBRPC_WC_DOM_READY',
  WBRPC_WC_DID_FRAME_FINISH_LOAD: 'WBRPC_WC_DID_FRAME_FINISH_LOAD',
  WBRPC_WC_DID_FINISH_LOAD: 'WBRPC_WC_DID_FINISH_LOAD',
  WBRPC_PERMISSION_REQUESTS_CHANGED: 'WBRPC_PERMISSION_REQUESTS_CHANGED',

  // Tasks
  WBRPC_CLOSE_WINDOW: 'WBRPC_CLOSE_WINDOW',
  WBRPC_SEND_INPUT_EVENT: 'WBRPC_SEND_INPUT_EVENT',
  WBRPC_SEND_INPUT_EVENTS: 'WBRPC_SEND_INPUT_EVENTS',
  WBRPC_SHOW_ASYNC_MESSAGE_DIALOG: 'WBRPC_SHOW_ASYNC_MESSAGE_DIALOG',
  WBRPC_RESOLVE_PERMISSION_REQUEST: 'WBRPC_RESOLVE_PERMISSION_REQUEST',
  WBRPC_OPEN_RECENT_LINK: 'WBRPC_OPEN_RECENT_LINK',
  WBRPC_OPEN_READING_QUEUE_LINK: 'WBRPC_OPEN_READING_QUEUE_LINK',

  // Getters
  WBRPC_SYNC_GET_INITIAL_HOST_URL: 'WBRPC_SYNC_GET_INITIAL_HOST_URL',
  WBRPC_SYNC_GET_GUEST_PRELOAD_CONFIG: 'WBRPC_SYNC_GET_GUEST_PRELOAD_CONFIG',
  WBRPC_SYNC_GET_EXTENSION_CS_PRELOAD_CONFIG: 'WBRPC_SYNC_GET_EXTENSION_CS_PRELOAD_CONFIG',
  WBRPC_SYNC_GET_EXTENSION_HT_PRELOAD_CONFIG: 'WBRPC_SYNC_GET_EXTENSION_HT_PRELOAD_CONFIG',
  WBRPC_GET_UPDATER_CONFIG: 'WBRPC_GET_UPDATER_CONFIG'
})
