module.exports = Object.freeze({
  // Events
  WCRPC_DOM_READY: 'WCRPC_DOM_READY',

  // Tasks
  WCRPC_CLOSE_WINDOW: 'WCRPC_CLOSE_WINDOW',
  WCRPC_GUEST_CLOSE_WINDOW: 'WCRPC_GUEST_CLOSE_WINDOW',
  WCRPC_SEND_INPUT_EVENT: 'WCRPC_SEND_INPUT_EVENT',
  WCRPC_SEND_INPUT_EVENTS: 'WCRPC_SEND_INPUT_EVENTS',
  WCRPC_SHOW_ASYNC_MESSAGE_DIALOG: 'WCRPC_SHOW_ASYNC_MESSAGE_DIALOG',

  // Getters
  WCRPC_SYNC_GET_OPENER_INFO: 'WCRPC_SYNC_GET_OPENER_INFO'
})
