module.exports = Object.freeze({
  // Events
  WCRPC_DOM_READY: 'WCRPC_DOM_READY',
  WCRPC_DID_FRAME_FINISH_LOAD: 'WCRPC_DID_FRAME_FINISH_LOAD',
  WCRPC_DID_FINISH_LOAD: 'WCRPC_DID_FINISH_LOAD',
  WCRPC_PERMISSION_REQUESTS_CHANGED: 'WCRPC_PERMISSION_REQUESTS_CHANGED',

  // Tasks
  WCRPC_CLOSE_WINDOW: 'WCRPC_CLOSE_WINDOW',
  WCRPC_SEND_INPUT_EVENT: 'WCRPC_SEND_INPUT_EVENT',
  WCRPC_SEND_INPUT_EVENTS: 'WCRPC_SEND_INPUT_EVENTS',
  WCRPC_SHOW_ASYNC_MESSAGE_DIALOG: 'WCRPC_SHOW_ASYNC_MESSAGE_DIALOG',
  WCRPC_RESOLVE_PERMISSION_REQUEST: 'WCRPC_RESOLVE_PERMISSION_REQUEST',
  WCRPC_OPEN_RECENT_LINK: 'WCRPC_OPEN_RECENT_LINK',
  WCRPC_OPEN_READING_QUEUE_LINK: 'WCRPC_OPEN_READING_QUEUE_LINK',
  WCRPC_OPEN_URL_IN_TOP_LEVEL_SERVICE: 'WCRPC_OPEN_URL_IN_TOP_LEVEL_SERVICE',

  // Getters
  WCRPC_SYNC_GET_INITIAL_HOST_URL: 'WCRPC_SYNC_GET_INITIAL_HOST_URL',
  WCRPC_SYNC_GET_GUEST_PRELOAD_CONFIG: 'WCRPC_SYNC_GET_GUEST_PRELOAD_CONFIG',
  WCRPC_SYNC_GET_EXTENSION_CS_PRELOAD_CONFIG: 'WCRPC_SYNC_GET_EXTENSION_CS_PRELOAD_CONFIG',
  WCRPC_SYNC_GET_EXTENSION_HT_PRELOAD_CONFIG: 'WCRPC_SYNC_GET_EXTENSION_HT_PRELOAD_CONFIG',
  WCRPC_GET_UPDATER_CONFIG: 'WCRPC_GET_UPDATER_CONFIG'
})
