const TOUR_STEPS = Object.freeze({
  NONE: 'NONE',
  WHATS_NEW: 'WHATS_NEW',
  APP_WIZARD: 'APP_WIZARD',
  SUPPORT_CENTER: 'SUPPORT_CENTER',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  SETTINGS: 'SETTINGS',
  EXPANDER: 'EXPANDER'
})
const TOUR_STEPS_ORDER = Object.freeze([
  TOUR_STEPS.NONE,
  TOUR_STEPS.WHATS_NEW,
  TOUR_STEPS.APP_WIZARD,
  TOUR_STEPS.SUPPORT_CENTER,
  TOUR_STEPS.ADD_ACCOUNT,
  TOUR_STEPS.SETTINGS,
  TOUR_STEPS.EXPANDER
])

module.exports = {
  TOUR_STEPS,
  TOUR_STEPS_ORDER
}
