module.exports = {
  CLIENT_ID: 'CLIENT_ID',
  CLIENT_TOKEN: 'CLIENT_TOKEN',
  ANALYTICS_ID: 'ANALYTICS_ID',
  CREATED_TIME: 'CREATED_TIME',
  USER: 'USER',
  USER_EPOCH: 'USER_EPOCH',

  EXTENSIONS: 'EXTENSIONS',
  WIRE_CONFIG: 'WIRE_CONFIG'
}
