const TEMPLATE_TYPES = {
  GOOGLE_MAIL: 'GOOGLE_MAIL',
  GOOGLE_INBOX: 'GOOGLE_INBOX',
  OUTLOOK: 'OUTLOOK',
  OFFICE365: 'OFFICE365',
  SLACK: 'SLACK',
  TRELLO: 'TRELLO',
  GENERIC: 'GENERIC',
  CONTAINER: 'CONTAINER'
}

export default TEMPLATE_TYPES