const SERVICE_TYPES = Object.freeze({
  UNKNOWN: 'UNKNOWN',

  CONTAINER: 'CONTAINER',
  GENERIC: 'GENERIC',
  SLACK: 'SLACK',
  TRELLO: 'TRELLO',

  // Google
  GOOGLE_MAIL: 'GOOGLE_MAIL',
  GOOGLE_INBOX: 'GOOGLE_INBOX',
  GOOGLE_DRIVE: 'GOOGLE_DRIVE',
  GOOGLE_CONTACTS: 'GOOGLE_CONTACTS',
  GOOGLE_KEEP: 'GOOGLE_KEEP',
  GOOGLE_CALENDAR: 'GOOGLE_CALENDAR',
  GOOGLE_PHOTOS: 'GOOGLE_PHOTOS',
  GOOGLE_HANGOUTS: 'GOOGLE_HANGOUTS',
  GOOGLE_PLUS: 'GOOGLE_PLUS',
  GOOGLE_ANALYTICS: 'GOOGLE_ANALYTICS',
  GOOGLE_YOUTUBE: 'GOOGLE_YOUTUBE',
  GOOGLE_ALLO: 'GOOGLE_ALLO',
  GOOGLE_DOCS: 'GOOGLE_DOCS',
  GOOGLE_SHEETS: 'GOOGLE_SHEETS',
  GOOGLE_SLIDES: 'GOOGLE_SLIDES',
  GOOGLE_MUSIC: 'GOOGLE_MUSIC',
  GOOGLE_ADMIN: 'GOOGLE_ADMIN',
  GOOGLE_FI: 'GOOGLE_FI',
  GOOGLE_CLASSROOM: 'GOOGLE_CLASSROOM',
  GOOGLE_CHAT: 'GOOGLE_CHAT',
  GOOGLE_VOICE: 'GOOGLE_VOICE',

  // Microsoft
  MICROSOFT_MAIL: 'MICROSOFT_MAIL',
  MICROSOFT_ONEDRIVE: 'MICROSOFT_ONEDRIVE',
  MICROSOFT_CONTACTS: 'MICROSOFT_CONTACTS',
  MICROSOFT_TASKS: 'MICROSOFT_TASKS',
  MICROSOFT_CALENDAR: 'MICROSOFT_CALENDAR',
  MICROSOFT_WORD: 'MICROSOFT_WORD',
  MICROSOFT_EXCEL: 'MICROSOFT_EXCEL',
  MICROSOFT_POWERPOINT: 'MICROSOFT_POWERPOINT',
  MICROSOFT_ONENOTE: 'MICROSOFT_ONENOTE',
  MICROSOFT_TEAMS: 'MICROSOFT_TEAMS',
  MICROSOFT_TODO: 'MICROSOFT_TODO'
})

export default SERVICE_TYPES
